test: refactor Leveraged Buy testCase
para-space/paraspace-core pull request #156
Opened 2022-11-03 12:17 UTC by ww36315610

## Security Checklist

- [ ] 1. Re-Entrancy
- [ ] 2. Arithmetic Over/Under Flows
- [ ] 3. Unexpected Ether
- [ ] 4. Delegatecall
- [ ] 5. Default Visibilities
- [ ] 6. Entropy Illusion
- [ ] 7. External Contract Referencing
- [ ] 8. Short Address/Parameter Attack (off chain)
- [ ] 9. Unchecked CALL Return Values
- [ ] 10. Race Conditions / Front Running
- [ ] 11. Denial Of Service (DOS)
- [ ] 12. Block Timestamp Manipulation
- [ ] 13. Constructors with Care
- [ ] 14. Uninitialized Storage Pointers
- [ ] 15. Floating Points and Precision
- [ ] 16. Tx.Origin Authentication
- [ ] 17. Address.isContract Re-Entrancy via Constructor

### ⚠️ NOTES ⚠️

Make sure to think about each of these exploits in this PR.

2022-11-07 02:32 UTC, alannotnerd requested changes

2022-11-07 02:32 UTC, alannotnerd commented on test-suites/_pool_marketplace_buy_with_credit.spec.ts
> +  let startAmount: BigNumber;
use fixture

2022-11-07 03:28 UTC, alannotnerd commented
Pls fix typos

2022-11-08 14:47 UTC, ivans083 approved these changes

2022-11-09 08:56 UTC, alannotnerd commented
Can you pls resolve the comments?

2022-11-10 02:27 UTC, closed without merging