test: refactor unit test acl manager
para-space/paraspace-core pull request #191
Opened 2022-11-10 13:21 UTC by RealLau

## Security Checklist

- [ ] 1. Re-Entrancy
- [ ] 2. Arithmetic Over/Under Flows
- [ ] 3. Unexpected Ether
- [ ] 4. Delegatecall
- [ ] 5. Default Visibilities
- [ ] 6. Entropy Illusion
- [ ] 7. External Contract Referencing
- [ ] 8. Short Address/Parameter Attack (off chain)
- [ ] 9. Unchecked CALL Return Values
- [ ] 10. Race Conditions / Front Running
- [ ] 11. Denial Of Service (DOS)
- [ ] 12. Block Timestamp Manipulation
- [ ] 13. Constructors with Care
- [ ] 14. Uninitialized Storage Pointers
- [ ] 15. Floating Points and Precision
- [ ] 16. Tx.Origin Authentication
- [ ] 17. Address.isContract Re-Entrancy via Constructor

### ⚠️ NOTES ⚠️

Make sure to think about each of these exploits in this PR.

2022-11-15 02:11 UTC, alannotnerd commented on test-suites/_base_acl_manager.spec.ts
> +  ...testEnv
```suggestion
 ...testEnv,
  aclManager
```

2022-11-15 02:16 UTC, alannotnerd requested changes
Pls resolve the CI issue and the conflicts.

2022-11-16 10:30 UTC, alannotnerd requested changes
Pls resolve the CI failure

2022-11-16 13:45 UTC, ivansolomonoff commented
Make sure to remove the original test script file within this PR as well.

2022-11-17 07:02 UTC, closed without merging